### ISSUE TITLE
Changing rotation of image crashes game.

### ISSUE THREAD

**Issue by WesternSpace** [austinvaness/CameraLCD#1]
It causes this error when you try to move the rotation slider:
`2021-09-12 22:45:34.114 - Thread:  24 ->  Exception occurred: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at VRage.Render11.Resources.Internal.MyGeneratedTexture.Reset(DataBox[] dataBoxes)
   at VRage.Render11.Resources.MyGeneratedTextureManager.Reset(MyGeneratedTexture tex, Byte[] data, Int32 nchannels)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at avaness.CameraLCD.Wrappers.MyFileTextureManager.ResetGeneratedTexture(String name, Byte[] data)
   at avaness.CameraLCD.CameraTSS.OnDrawScene()
   at avaness.CameraLCD.CameraLCD.OnDrawScene()
   at VRageRender.MyRender11.DrawScene_Patch1()
   at VRageRender.MyRender11.FullDraw(Boolean draw)
   at VRageRender.MyRender11.Draw(Boolean draw)
   at VRageRender.ExternalApp.MyRenderThread.Draw()
   at VRageRender.ExternalApp.MyRenderThread.RenderFrame(Boolean async)
   at VRageRender.ExternalApp.MyRenderThread.RenderCallback(Boolean async)
   at VRageRender.ExternalApp.MyRenderThread.RenderThreadStart(Object param)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2021-09-12 22:45:34.115 - Thread:  24 ->  InnerException: 
2021-09-12 22:45:34.115 - Thread:  24 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at VRage.Render11.Resources.Internal.MyGeneratedTexture.Reset(DataBox[] dataBoxes)
   at VRage.Render11.Resources.MyGeneratedTextureManager.Reset(MyGeneratedTexture tex, Byte[] data, Int32 nchannels)`

Since you probably won't ever rotate the image, disabling the rotation slider is probably the best solution.
![Screenshot (1485)](https://user-images.githubusercontent.com/80211714/133017206-5a26758d-a4be-41d1-b910-d0c162b03be5.png)

**Comment by austinvaness** [comment]
I have added a workaround for this but I am still unsure why the crash happens.
